name: wwwwze git page
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install and Build
        run: |
          npm install
          npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.9
      with:
        branch: gh-pages
        folder: dist
        ssh-key: ${{ secrets.ACCESS_TOKEN }}
# https://github.com/marketplace/actions/deploy-to-github-pages
